### ISSUE TITLE
SA 9.4.15 sending UDP packets in port 29765

### ISSUE THREAD

**Issue by rogermiranda1000** [regzo2/PicoStreamingAssistantFTUDP#4]
Streaming Assistant (in the headset) is sending the UDP packets using the port 29765:
![image](https://github.com/regzo2/PicoStreamingAssistantFTUDP/assets/30045337/0b64b2ed-32f0-4b70-ac2c-9a0fbcd221dd)

According to your constant [PORT_NUMBER](https://github.com/regzo2/PicoStreamingAssistantFTUDP/blob/274762b9ef576443f8081ac9e4f854ff2efc24df/PicoStreamingAssistantFTUDP/Pico4SAFTExtTrackingModule.cs#L17), it should be 29763. I've loaded one beta version (9.4.10) and it does send the UDP packets on 29763, so maybe they have changed the port in the latest version?

**Comment by TheBug233** [comment]
Now that the internal beta version of PICO Streaming Assistant has been leaked, this matter can finally be resolved. After you submitted this version, the 1.3 module caused the PICO streaming assistant to repeatedly restart PICO's own body tracking data port due to port occupation. Although it will not consume too many resources on most people's computers, 1.2 version of the module does not have this problem
